version: "3.7"
services:

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.3
    hostname: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://localhost:9200
      ELASTICSEARCH_HOSTS: http://localhost:9200
