site_name: Tracardi Documentation
site_description: Open-source Data Platform
site_url: https://www.tracardi.com
theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/tracardi
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/tracardi
    - icon: fontawesome/brands/github
      link: https://github.com/atopmie/tracardi
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UC0atjYqW43MdqNiSJBvN__Q
copyright: Copyright &copy; 2020 - 2021 Tracardi
repo_url: https://github.com/atompie/tracardi
repo_name: atompie/tracardi
nav:
  - index.md
  - Installation:
      - installation/index.md
      - installation/building_docker_from_source.md
      - Configuration:
          - installation/tracardi_configuration.md
      - Elasticsearch:
        - installation/elasticsearch/connecting_elasticsearch_cluster.md
        - installation/elasticsearch/elastic_authentication.md
        - installation/elasticsearch/sql_translation_configuration.md
        - installation/elasticsearch/elastic_max_connections.md
      - installation/truble_shooting.md
  - Running:
      - running/index.md
  - Getting started:
    - getting_started/index.md
    - getting_started/code_definitions.md
    - getting_started/event_tracking.md
    - getting_started/profile_merging.md
    - getting_started/profile_segmentation.md
  - Data:
      data/index.md
  - Configuration:
    - Sources:
        - sources/index.md
    - Web page integration:
        - js-integration/index.md
    - Flow:
        - flow/index.md
        - Actions:
            - Operations:
                - flow/actions/update_profile_action.md
                - flow/actions/merge_profiles_action.md
                - flow/actions/segment_profiles_action.md
            - flow/actions/if_action.md
            - flow/actions/detect_client_agent_action.md
            - Stats:
              - flow/actions/increment_action.md
              - flow/actions/decrement_action.md
              - flow/actions/increase_views_action.md
              - flow/actions/increase_visits_action.md
            - flow/actions/new_event_action.md
        - Notations:
            - notations/index.md
            - notations/dot_notation.md
            - notations/logic.md
            - notations/math.md
  - Api:
      - api/index.md
  - support_us.md
  - attribution.md
  - software_license.md
  - documentation_license.md

